name: pokemon_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx:
  flutter_mobx:
  cached_network_image: ^2.0.0
  md2_tab_indicator: ^1.0.2
  provider: ^4.0.1
  flutter_staggered_animations: "0.1.2"
  sliding_sheet: ^0.2.4
  flutter_icons: ^1.0.0+1
  intl: ^0.16.1
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen:
  build_runner:

flutter:
  uses-material-design: true
  assets:
   - assets/images/pokeball.png
   - assets/images/pokeball_dark.png
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
